# This file tells "conda" what to install in order to run the code. Things will
# be installed in a separate environment (with the name defined below) so that
# they don't interfere with other programs/projects.
name: dissertation
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  # For executing tasks
  - make
  # For running LaTeX to build the dissertation PDF
  - tectonic
  # The basic Scipy stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - xarray
  # For spatial data and grids
  - netcdf4
  - pyproj
  # Jupyter notebook
  - jupyter
  - jupyterlab
  # The Fatiando a Terra packages
  - verde
  - harmonica
  - boule
  - pooch
